version: '3.9'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /home/siedler/mongodb/database:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
  server:
    build: .
    container_name: house-rental-notifier
    command: npm start
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - MONGODB_URI=mongodb://mongodb:27017
